python adaVAE.py --batch-sizes 100 --dataset yahoo_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 0.0 &&\
python adaVAE.py --batch-sizes 100 --dataset yahoo_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 0.5 &&\
python adaVAE.py --batch-sizes 100 --dataset yahoo_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 1.0 &&\
python adaVAE.py --batch-sizes 100 --dataset yahoo_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 5.0 &&\
python adaVAE.py --batch-sizes 100 --dataset yahoo_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 10.0 &&\
python adaVAE.py --batch-sizes 100 --dataset yahoo_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 25.0 &&\
python adaVAE.py --batch-sizes 100 --dataset yahoo_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 50.0 &&\
python adaVAE.py --batch-sizes 100 --dataset yahoo_data --max_length 32 --add_attn --adapter_size 128 --iterations 10000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 50.0 &&\
python adaVAE.py --batch-sizes 100 --dataset penn_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 0.0 &&\
python adaVAE.py --batch-sizes 100 --dataset penn_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 0.5 &&\
python adaVAE.py --batch-sizes 100 --dataset penn_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 1.0 &&\
python adaVAE.py --batch-sizes 100 --dataset penn_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 5.0 &&\
python adaVAE.py --batch-sizes 100 --dataset penn_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 10.0 &&\
python adaVAE.py --batch-sizes 100 --dataset penn_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 25.0 &&\
python adaVAE.py --batch-sizes 100 --dataset penn_data --max_length 32 --add_attn --adapter_size 128 --iterations 6000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 50.0 &&\
python adaVAE.py --batch-sizes 100 --dataset penn_data --max_length 32 --add_attn --adapter_size 128 --iterations 10000 --latent_size 32 --encoder_n_layer 8 --decoder_n_layer 12 --adapter_init bert --attn_mode none --kl_rate 50.0